import {
  Priority,
  Project,
  Status,
  Task,
  TaskStatus,
  Team,
  User,
} from './core/models/project.model';

export const users: User[] = [
  { firstName: 'John', lastName: 'Doe', userName: 'john_doe' },
  { firstName: 'Jane', lastName: 'Smith', userName: 'jane_smith' },
  { firstName: 'Michael', lastName: 'Johnson', userName: 'michael_johnson' },
  { firstName: 'Anna', lastName: 'Williams', userName: 'anna_williams' },
  { firstName: 'Olivia', lastName: 'Brown', userName: 'olivia_brown' },
  { firstName: 'Sophia', lastName: 'Jones', userName: 'sophia_jones' },
  { firstName: 'Isabella', lastName: 'Garcia', userName: 'isabella_garcia' },
  { firstName: 'Mia', lastName: 'Martinez', userName: 'mia_martinez' },
  { firstName: 'Emily', lastName: 'Davis', userName: 'emily_davis' },
  {
    firstName: 'Elizabeth',
    lastName: 'Rodriguez',
    userName: 'elizabeth_rodriguez',
  },
  {
    firstName: 'Alexis',
    lastName: 'Hernandez',
    userName: 'alexis_hernandez',
  },
  {
    firstName: 'Ella',
    lastName: 'Lopez',
    userName: 'ella_lopez',
  },
];

const teams: Team[] = [
  {
    id: '1',
    name: 'Frontend Team',
    description: 'Team responsible for frontend development',
    members: [users[0], users[1], users[2], users[3], users[10], users[11]],
  },
  {
    id: '2',
    name: 'Backend Team',
    description: 'Team responsible for backend development',
    members: [users[4], users[5], users[6], users[7]],
  },
  {
    id: '3',
    name: 'QA Team',
    description: 'Team responsible for quality assurance',
    members: [users[8], users[9]],
  },
];

const tasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    users: [users[0], users[1], users[10], users[11]],
    name: 'Develop Header',
    status: TaskStatus.InProgress,
    priority: Priority.High,
    dueDate: '2024-05-01',
  },
  {
    id: '2',
    projectId: '1',
    users: [users[2], users[3]],
    name: 'Develop Sidebar',
    status: TaskStatus.NotStarted,
    priority: Priority.Medium,
    dueDate: '2024-06-01',
  },
  {
    id: '3',
    projectId: '1',
    users: [users[4], users[5]],
    name: 'Develop API',
    status: TaskStatus.Completed,
    priority: Priority.Low,
    dueDate: '2024-07-01',
  },
  {
    id: '4',
    projectId: '1',
    users: [users[6], users[7]],
    name: 'Database Design',
    status: TaskStatus.Completed,
    priority: Priority.Medium,
    dueDate: '2024-08-01',
  },
  {
    id: '5',
    projectId: '1',
    users: [users[8], users[9]],
    name: 'Testing',
    status: TaskStatus.InProgress,
    priority: Priority.High,
    dueDate: '2024-09-01',
  },
];

export const dummyProjects: Project[] = [
  {
    id: '1',
    name: 'Website Redesign',
    description: 'Complete redesign of the company website to improve UX/UI.',
    startDate: '2024-01-01',
    endDate: '2024-10-22',
    completedTasks: 5,
    totalTasks: 10,
    status: Status.InProgress,
    owner: users[0],
    members: users,
    tasks: tasks.filter((task) => task.projectId === '1'),
    teams: [teams[0], teams[1], teams[2]],
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Development of a new mobile application for iOS and Android.',
    startDate: '2024-02-01',
    endDate: '2024-10-18',
    completedTasks: 3,
    totalTasks: 8,
    status: Status.Completed,
    owner: users[4],
    members: [users[4], users[5]],
    tasks: tasks.filter((task) => task.projectId === '2'),
    teams: [teams[1]],
  },
  {
    id: '3',
    name: 'E-commerce Platform',
    description: 'Building a new e-commerce platform with advanced features.',
    startDate: '2024-03-01',
    endDate: '2024-08-01',
    completedTasks: 7,
    totalTasks: 15,
    status: Status.Completed,
    owner: users[6],
    members: [users[6], users[7]],
    tasks: tasks.filter((task) => task.projectId === '3'),
    teams: [teams[2]],
  },
  {
    id: '4',
    name: 'Cloud Migration',
    description: 'Migrating all company data and applications to the cloud.',
    startDate: '2024-04-01',
    endDate: '2025-01-01',
    completedTasks: 2,
    totalTasks: 5,
    status: Status.InProgress,
    owner: users[8],
    members: [users[8], users[9]],
    tasks: tasks.filter((task) => task.projectId === '4'),
    teams: [teams[0]],
  },
  {
    id: '5',
    name: 'Marketing Campaign',
    description:
      'Launching a new marketing campaign to increase brand awareness.',
    startDate: '2024-05-01',
    endDate: '2024-12-15',
    completedTasks: 6,
    totalTasks: 12,
    status: Status.InProgress,
    owner: users[0],
    members: [users[0], users[1]],
    tasks: tasks.filter((task) => task.projectId === '5'),
    teams: [teams[1], teams[2]],
  },
];
