services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NG_APP_API_URL: ${NG_APP_API_URL}
        NG_APP_SOCKET_URL: ${NG_APP_SOCKET_URL}
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - client-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - client-network
      - server-network
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - server-network

networks:
  client-network:
  server-network:

volumes:
  postgresql-data:
