spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json

logging:
  level:
    root: INFO

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 300 # 5min
      refresh-token:
        expiration: 1800 # 30min
    frontend:
      url: ${FRONTEND_URL}

server:
  servlet:
    context-path: /api/v1/
  port: 8080
