spring:
  jwt:
    key:
  datasource:
    url: jdbc:postgresql://localhost:3333/manageit
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: i1OoH6mKPAxzFfJ4R3eOAtYPc5jh0az4RoU9nk10HOnRFZtXpGLXdj4B1beAoTWx
      expiration: 1440000